platformName: Android

#deviceName: hw
#udid: 8GPDU18719000594
#platformVersion: 9


#deviceName: op
#udid: 1f344c14
#platformVersion: 8.1.0



#platformVersion: 8.1.0
#udid: 8FS7N16916007633
#deviceName: HUAWEI P9 Plus

#udid: c485aa18
#deviceName: Mi Note 3
#platformVersion: 8.1.0

udid: LE67A06170270823
deviceName: Le X620
platformVersion: 6.0




#appname: cxjz.apk
noReset: True
unicodeKeyboard: True
resetKeyboard: True

automationName: Uiautomator2

#fullReset: False
chromeOptions: {'androidProcess': 'com.tencent.mm:appbrand0'}

appPackage: com.tencent.mm
appActivity: com.tencent.mm.ui.LauncherUI
ip: 127.0.0.1
port: 4723